name: Managed
on:
  push:
    branches:
      - main
      - pmm-*
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*

  pull_request:
    paths-ignore:
      - 'admin/**'
      - 'agent/**'
      - 'api-tests/**'
      - 'cli-tests/**'
      - 'docs/**'
      - 'qan-api2/**'
      - 'update/**'
      - 'vmproxy/**'

jobs:
  test:
    name: Tests
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    strategy:
      fail-fast: false

    env:
      PMM_SERVER_IMAGE: perconalab/pmm-server:dev-latest
      AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
      OAUTH_PMM_CLIENT_ID: ${{ secrets.OAUTH_PMM_CLIENT_ID }}
      OAUTH_PMM_CLIENT_SECRET: ${{ secrets.OAUTH_PMM_CLIENT_SECRET }}
      DEVCONTAINER_CACHE_ENABLED: false

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Download tools
        if: ${{ fromJSON(env.DEVCONTAINER_CACHE_ENABLED) }}
        run: |
          pushd tools && go mod download -x
          popd        && go mod download -x

